export const COURSES: any =  {
    1: {
      id: 1,
      name: 'Rush Lusk Educate Together Ns',
      address1: 'Rathmore Rd',
      address2: 'Lusk',
      address3: '',
      phone: '(01) 8430525',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Violin', 'Chess', 'Art & Craft', 'Lego Club',
                  'Dyslexia Workshop', 'GAA', 'Ukelele Club', 'Piano',
                  'Basketball', 'Project Fashion'],
      lat: 53.5289465480972,
      long: -6.15690613123526,
      website: '"http://ralet.ie/"',
      seqNo: 0,
    },
    2: {
      id: 2,
      name: 'Mary Mother Of Hope Senior Ns',
      address1: 'Littlepace, Castaheaney',
      address2: 'Dublin 15',
      address3: ' ',
      phone: '(01) 8128693',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Gaelic Football', 'Camogie, Hurling & Athletics', 'Tag Rugby',
                    'Junior Hurlers', 'Basketball ', 'Football',
                    'Minecraft Club and Mind Rising', 'Drumming Workshop'],
      lat: 53.4044437677559,
      long: -6.42466733348594,
      website: 'https://www.hopens.ie/',
      seqNo: 2
    },
   4: {
      id: 4,
      name: 'Saint Philip The Apostle  Jns',
      address1: 'Mountview Road',
      address2: 'Dublin 15',
      address3: ' ',
      phone: '(01) 8212992',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
      completion_Prog: 'Program Available',
      activities: [''],
      lat: 53.3902759865971,
      long: -6.407382917605,
      website: '',
      seqNo: 4
    },
    5: {
      id: 5,
      name: 'Saint Francis Xavier Sns',
      address1: 'Roselawn Road',
      address2: 'Castleknock',
      address3: 'Dublin 15',
      phone: '(01) 8211121',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: [''],
      lat: 53.3827223864593,
      long: -6.38334297475873,
      website: 'http://sfxns.ie/seniorschool/',
      seqNo: 5
    },
    6: {
      id: 6,
      name: 'Bayside Jns (Muire Agus Iosef)',
      address1: 'Verbena Avenue',
      address2: 'Sutton',
      address3: 'Dublin 13',
      phone: '(01) 8326524',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: [''],
      lat: 53.3893444134756,
      long: -6.14725231097875,
      website: 'https://baysidejunior.ie/',
      seqNo: 6
    },
    7: {
      id: 7,
      name: 'Saint Mologas Ns',
      address1: 'Bremore',
      address2: 'Balbriggan',
      address3: 'Dublin',
      phone: '(01) 8413133',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Athletics', 'Gymnastics', 'Dance'],
      lat: 53.6158565903141,
      long: -6.19034968085074,
      website: '"http://stmolaga.scoilnet.ie/blog/"',
      seqNo: 7
    },
    8: {
      id: 8,
      name: 'Balbriggan Educate Together',
      address1: 'Hamlet Lane',
      address2: 'Moylaragh',
      address3: 'Balbriggan',
      phone: '(01) 6904635',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
      completion_Prog: 'Program Available',
      activities: ['Choir', 'GAA', 'Soccer', 'Rugby', 'Cycling', 'Drams', 'Music'],
      lat: 53.6125330756283,
      long: -6.20650185613338,
      website: 'http://balbrigganetns.scoilnet.ie/blog/',
      seqNo: 8
    },
    9: {
      id: 9,
      name: 'Saint Patricks National School',
      address1: 'Diswellstown',
      address2: 'Dubiln 15',
      address3: ' ',
      phone: '(01) 8249930',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Classical and Acoustic Guitar', 'Speech & Drama', 'Irish Dancing',
                  'Basketbal', 'Tennis ', 'Badminton', 'GAA '],
      lat: 53.3692097523722,
      long: -6.38814974279032,
      website: 'http://www.stpatricksns.ie/',
      seqNo: 9
    },
    10: {
      id: 10,
      name: 'Scoil Thomais',
      address1: 'Laurel Lodge',
      address2: 'Castleknock',
      address3: 'Dublin 15',
      phone: '(01) 8201022',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Science Club', 'Baking ', 'Basketball ', 'Gymnastics', 'Guitar',
                    'Scratch Coding', 'Art & Craft ', 'Film Making', 'Beginners’ Coding ' ],
      lat: 53.3781604561254,
      long: -6.37781693388738,
      website: 'https://www.scoilthomais.ie/',
      seqNo: 10
    },
    11: {
      id: 11,
      name: 'St Patricks Jns/Corduff Ns',
      address1: 'Blackcourt Road',
      address2: 'Corduff',
      address3: 'Dublin 15',
      phone: '(01) 8211546',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
      completion_Prog: 'Program Available',
      activities: ['Gaelic Football', 'Soccer', 'Basketball',  'Athletics'],
      lat: 53.3988995049934,
      long: -6.37569150077036,
      website: 'http://www.stpatrickscorduff.ie/',
      seqNo: 11
    },
    12: {
      id: 12,
      name: 'Ladyswell National School',
      address1: 'Ladyswell',
      address2: 'Mulhuddart',
      address3: 'Dublin 15',
      phone: '(01) 8204255',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
      completion_Prog: 'Program Available',
      activities: [''],
      lat: 53.4059732702325,
      long: -6.3919037401449,
      website: '',
      seqNo: 12
    },
    13: {
      id: 13,
      name: 'Mulhuddart National School',
      address1: 'Mulhuddart Village',
      address2: 'Dublin 15',
      address3: ' ',
      phone: '(01) 8210623',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['GAA', 'Basketball'],
      lat: 53.4146752800165,
      long: -6.39227934103521,
      website: 'https://stlukesns.ie/',
      seqNo: 13
    },
    14: {
      id: 14,
      name: 'Tyrellstown Educate Together',
      address1: 'Powerstown Road',
      address2: 'Tyrellstown',
      address3: 'Dublin 15',
      phone: '(01) 8273140',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Religion', 'Mathemagician', 'Lego', 'Art & Crafts', 'Coding',
                    'Zumba', 'Dancing', 'Zen Zone' ],
      lat: 53.4146479295021,
      long: -6.39024989908105,
      website: 'http://tetns.ie/',
      seqNo: 14
    },

    17: {
      id: 17,
      name: 'Saint Colmcilles Boys National School',
      address1: 'Chapel Lane',
      address2: 'Swords',
      address3: 'Co. Dublin',
      phone: '(01) 8405132',
      school_Level: 'Primary',
      mixed_Status: 'Boys',
      fee_paying: 'No Fee',
      completion_Prog: 'Program Available',
      activities: ['Soccer', 'Athletics', 'Gaelic Footbal'],
      lat: 53.4584828670109,
      long: -6.2147721001359,
      website: 'http://www.colmcilles.net/',
      seqNo: 17
    },
    19: {
      id: 19,
      name: 'Scoil Realt Na Mara',
      address1: 'Balbriggan Road',
      address2: 'Skerries',
      address3: 'Balbriggan',
      phone: '(01) 8490049',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Football – Peil Gaelach', 'Athletics – Lúthchleasaíocht', 'GAA – CLG ',
                    'Rugby – Rugbaí', 'Cricket – Cruicéad ', 'Hockey – Haca',
                  'SCHOOL CHOIR - CÓR NA SCOILE'],
      lat: 53.580314399909,
      long: -6.1206978131954,
      website: 'https://realtnamara.ie/',
      seqNo: 19
    },
    20: {
      id: 20,
      name: 'Lusk National School (Sn Lusca)',
      address1: 'Chapel Road',
      address2: 'Lusk',
      address3: 'Co. Dublin',
      phone: '(01) 8437738',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Games Club', 'Sports', 'Music'],
      lat: 53.5291863342288,
      long: -6.16791665699562,
      website: 'http://www.luskns.ie/',
      seqNo: 20
    },
    21: {
      id: 21,
      name: 'Loughshinney National School (Saint Brendans/ Scoil N Breandan)',
      address1: 'Ballykea',
      address2: 'Skerries',
      address3: 'Balbriggan',
      phone: '(01) 8490394',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Swimming', 'Cricket', 'Gaelic Football & Hurling(Boys & Girls)', 'Irish Dancing',
                    'Tin Whistle', 'Rugby', '	Basketball', 'Soccer', 'Gymnastics', '	Athletics'],
      lat: 53.5464103754593,
      long: -6.09018257953956,
      website: 'http://loughshinnyns.ie/',
      seqNo: 21
    },
    22: {
      id: 22,
      name: 'Scoil Nais Caitriona- Saint Catherines National School',
      address1: 'Saint Catherines Avenue',
      address2: 'Rush',
      address3: 'Co. Dublin',
      phone: '(01) 8438266',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: [''],
      lat: 53.5350226302885,
      long: -6.0992697020554,
      website: 'http://www.stcatherinesns.ie/',
      seqNo: 22
    },
    23: {
      id: 23,
      name: 'Hedgestown Ns (Scoil Baile Falbhach)',
      address1: 'Jordanstown',
      address2: 'Lusk',
      address3: 'Co. Dublin',
      phone: '(01) 8438372',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: [''],
      lat: 53.5507115722196,
      long: -6.20756620503561,
      website: 'http://www.hedgestownns.com/',
      seqNo: 23
    },
    24: {
      id: 24,
      name: 'Oldtown National School (S N Muire An Sean Baile)',
      address1: 'Oldtown',
      address2: 'Co. Dublin',
      address3: ' ',
      phone: '(01) 8433420',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['GAA', 'Footbal'],
      lat: 53.5244717037047,
      long: -6.31850695020617,
      website: 'https://www.oldtownns.ie/',
      seqNo: 24
    },
    25: {
      id: 25,
      name: 'Mary Queen Of Ireland National School',
      address1: 'Toberburr',
      address2: 'Saint Margarets',
      address3: 'Swords',
      phone: '(01) 8404629',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
      completion_Prog: 'Program Available',
      activities: [''],
      lat: 53.4525756509884,
      long: -6.2925495316841,
      website: 'http://www.maryqueenofireland.ie/',
      seqNo: 25
    },
    26: {
      id: 26,
      name: 'Gaelscoil Oilibheir',
      address1: 'Snugborough Road',
      address2: 'Dublin 15',
      address3: ' ',
      phone: '(01) 8215277',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Erin Go Bragh -GAA Club', 'Tinneas', 'Lón', 'As Láthair'],
      lat: 53.3873745195204,
      long: -6.39780159301137,
      website: 'http://www.gaelscoiloilibheir.ie/',
      seqNo: 26
    },
    28: {
      id: 28,
      name: 'Saint Helens Senior School',
      address1: 'Limetree Avenue',
      address2: 'Portmarnock',
      address3: 'Dublin 13',
      phone: '(01) 8461808',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: [''],
      lat: 53.4389986271051,
      long: -6.13580350925631,
      website: 'http://www.helens.ie/',
      seqNo: 28
    },
    29: {
      id: 29,
      name: 'Saint Helens Junior School',
      address1: 'Limetree Avenue',
      address2: 'Portmarnock',
      address3: 'Dublin 13',
      phone: '(01) 8461763',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: [''],
      lat: 53.4399030334322,
      long: -6.1360722630568,
      website: 'https://sthelensjunior.com/',
      seqNo: 29
    },
    30: {
      id: 30,
      name: 'Swords Borough N S',
      address1: 'Church Road',
      address2: 'Swords',
      address3: 'Co. Dublin',
      phone: '(01) 8407036',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Girls’ Brigade', 'Boys’ Brigade', 'Swimming'],
      lat: 53.4574521100282,
      long: -6.22313009039377,
      website: 'www.oldboroughschool.ie',
      seqNo: 30
    },
    32: {
      id: 32,
      name: 'Milverton National School (Scoil Mobhi)',
      address1: 'Milverton',
      address2: 'Skerries',
      address3: 'Balbriggan',
      phone: '(01) 8492467',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Athletics', 'Gaelic Football', 'Cricket', 'Tag Rugby'],
      lat: 53.5646445212491,
      long: -6.14753412080114,
      website: 'http://www.scoilmoibhi.ie/',
      seqNo: 32
    },
    33: {
      id: 33,
      name: 'Balscadden National School',
      address1: 'Balscadden',
      address2: 'Balbriggan',
      address3: 'Co. Dublin',
      phone: '(01) 8412579',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Irish Dancing', 'GAA'],
      lat: 53.6152784596126,
      long: -6.23217712174507,
      website: 'http://www.balscadden.com/',
      seqNo: 33
    },
    34: {
      id: 34,
      name: 'Castleknock Educate Together National School',
      address1: 'Beechpark Avenue',
      address2: 'Dublin 15',
      address3: ' ',
      phone: '(01) 8219331',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Anyone4Science', 'Artzone', 'Beechpark Religion', 'Futsal Programme', 'Lego Challenge',
                    'Mowlds School of Irish Dancing', 'Spanish', 'Tennis'],
      lat: 53.3800111040008,
      long: -6.36279657705396,
      website: 'http://www.cetns.ie/',
      seqNo: 34
    },
    36: {
      id: 36,
      name: 'Sacred Heart National School',
      address1: 'Huntstown Way',
      address2: 'Huntstown',
      address3: 'Dublin 15',
      phone: '(01) 8216400',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Hurling', 'Gaelic Footbal', 'Soccer'],
      lat: 53.4025589560919,
      long: -6.41005253389049,
      website: 'http://sacredhearthuntstown.weebly.com/',
      seqNo: 36
    },
    37: {
      id: 37,
      name: 'Saint Philips Sns',
      address1: 'Mountview Road',
      address2: 'Clonsilla',
      address3: 'Dublin 15',
      phone: '(01) 8216101',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
      completion_Prog: 'Program Available',
      activities: ['GAA', 'Gardening Club', 'Scratch Club', 'Ladies Footbal', 'Ukelele', 'Zumba',
                    'Design and Build'],
      lat: 53.3896278385681,
      long: -6.40741120060094,
      website: 'http://stphilips.ie/',
      seqNo: 37
    },
    40: {
      id: 40,
      name: 'Saint Mochtas National School',
      address1: 'Porterstown Road',
      address2: 'Clonsilla',
      address3: 'Dublin 15',
      phone: '(01) 8210499',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Art', 'Gaelic Football', 'Hurling', 'Soccer', 'Athletics', 'Cricket'],
      lat: 53.3820015349048,
      long: -6.40516624801997,
      website: 'https://stmochtas.edublogs.org/',
      seqNo: 40
    },
    42: {
      id: 42,
      name: 'Scoil Bride (Saint Brigids) Boys School',
      address1: 'Castleknock Road',
      address2: 'Dublin 15',
      address3: ' ',
      phone: '(01) 8201299',
      school_Level: 'Primary',
      mixed_Status: 'Boys',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: [''],
      lat: 53.3843298514973,
      long: -6.37279344284397,
      website: 'www.scoilbhrideb.com',
      seqNo: 42
    },
    43: {
      id: 43,
      name: 'Scoil Bride (Saint Brigids) Girls School',
      address1: 'Castleknock Road',
      address2: 'Dublin 15',
      address3: 'Blanchardstown',
      phone: '(01) 8201717',
      school_Level: 'Primary',
      mixed_Status: 'Girls',
      fee_paying: 'No Fee',
      completion_Prog: 'N/A ',
      activities: [''],
      lat: 53.3845543199929,
      long: -6.3740337897356,
      website: 'https://www.scoilnaomhbrid.com/',
      seqNo: 43
    },
    44: {
      id: 44,
      name: 'Saint Marys School',
      address1: 'Grange Road',
      address2: 'Baldoyle',
      address3: 'Dublin 13',
      phone: '(01) 8325591',
      school_Level: 'Primary',
      mixed_Status: 'Girls',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Basketball', 'Gaelic Footbal', 'Tennis', 'Badminton', 'Table Tennis', 'TY Judo'],
      lat: 53.397950298878,
      long: -6.13779093684913,
      website: 'https://www.stmarysbaldoyle.org/',
      seqNo: 44
    },
    45: {
      id: 45,
      name: 'Bayside Sns (Muire Agus Iosef)',
      address1: 'Verbena Avenue',
      address2: 'Sutton',
      address3: 'Dublin 13',
      phone: '(01) 8393682',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Athletics', 'Ladies Gaelic Football', 'Basketball for Boys & Girls',
                   'Camogie', 'Gaelic Football', 'Hurling', 'Rugby', 'Soccer'],
      lat: 53.3897493623251,
      long: -6.14687817487823,
      website: 'http://www.baysidesns.ie/',
      seqNo: 45
    },
    46: {
      id: 46,
      name: 'Saint Patricks Jnr Mixed',
      address1: 'Beau-Piers Lane',
      address2: 'Skerries',
      address3: 'Balbriggan',
      phone: '(01) 8490836',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: [''],
      lat: 53.57804880607,
      long: -6.10940713836094,
      website: 'http://www.stps.ie/',
      seqNo: 46
    },
    47: {
      id: 47,
      name: 'Saint Patricks Snr Mixed',
      address1: 'Beau-Piers Lane',
      address2: 'Skerries',
      address3: 'Balbriggan',
      phone: '(01) 8490945',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['GAA', 'Chess', 'School Garden'],
      lat: 53.5779987496743,
      long: -6.1101673570477,
      website: 'http://www.stpatrickssns.com/',
      seqNo: 47
    },
    48: {
      id: 48,
      name: 'Holmpatrick National School',
      address1: 'Convent Lane',
      address2: 'Skerries',
      address3: 'Balbriggan',
      phone: '(01) 8491409',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['GAA', 'Hokey', 'Rugby'],
      lat: 53.5796715096608,
      long: -6.10752250290817,
      website: 'http://www.holmpatrickns.ie/',
      seqNo: 48
    },
    50: {
      id: 50,
      name: 'Baldoyle National School (Saints Peter & Paul)',
      address1: 'Brookstone Road',
      address2: 'Baldoyle',
      address3: 'Dublin 13',
      phone: '(01) 8322938',
      school_Level: 'Primary',
      mixed_Status: 'Boys',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Scratch', 'Buddy Reading', 'Music', 'Basketball', 'Trackside Tennis',
                  'Table Tennis', 'Boxing', 'Irish Dancing'],
      lat: 53.3964267730838,
      long: -6.13288327307307,
      website: 'https://www.stlaurencesbaldoyle.org/our-school.html',
      seqNo: 50
    },
    52: {
      id: 52,
      name: 'Burrow National School',
      address1: 'Howth Road',
      address2: 'Sutton',
      address3: 'Dublin 13',
      phone: '(01) 8325784',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Irish Dancing', 'Fencing', 'Guitar', 'Phelan School of Irish Dance', 'Girls Basketball',
                    'Violin', 'Hockey ', 'Catherine Beatty Drama Academy'],
      lat: 53.3912904823223,
      long: -6.10028481232697,
      website: 'http://burrowschool.ie/',
      seqNo: 52
    },
    53: {
      id: 53,
      name: 'Donabate Portrane Educate Together',
      address1: 'Ballisk Common',
      address2: 'Portrane Road',
      address3: 'Donabate',
      phone: '(01) 8434573',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['GAA', 'Athletics', 'Basketball', 'Cricket', 'Soccer'],
      lat: 53.4895633430219,
      long: -6.14663645057326,
      website: 'http://www.dpetns.ie/',
      seqNo: 53
    },
    60: {
      id: 60,
      name: 'Saint Bridgids National School',
      address1: 'Beechpark Lawn',
      address2: 'Castleknock',
      address3: 'Dublin 15',
      phone: '(01) 8214040',
      school_Level: 'Primary',
      mixed_Status: 'Mixed',
      fee_paying: 'No Fee',
       completion_Prog: 'N/A ',
      activities: ['Badminton', 'Rugby', 'Handball', 'Cross Country', 'Hurling',
                    'Gymnastics', 'Camogie', 'Cricket', 'Soccer'],
      lat: 53.3751386169793,
      long: -6.36220804059328,
      website: 'https://m.saintbrigids.ie/',
      seqNo: 60
    }
  };

export const LESSONS = {
    1: {
      id: 1,
      activitiesCopy: ['Violin', 'Chess', 'Art & Craft', 'Lego Club',
        'Dyslexia Workshop', 'GAA', 'Ukelele Club', 'Piano',
        'Basketball', 'Project Fashion'],
      lat: 53.5289465480972,
      long: -6.15690613123526,
      website: 'http://ralet.ie/',
      phone: '(01) 8430525',
      description: '',
      seqNo: 1,
      courseId: 1
    }
  };

export function findCourseById(courseId: number) {
    return COURSES[courseId];
  }

export function findLessonsForCourse(courseId: number) {
    return Object.values(LESSONS).filter(lesson => lesson.courseId === courseId);
  }
