export const COURSES: any =  {
    3: {
      id: 3,
      name: 'Mater Christi Secondary School',
      address1: 'Cappagh',
      address2: 'Dublin 11',
      address3: ' ',
      phone: '(01) 8343165',
      school_Level: 'Secondary',
      mixed_Status: 'Girls',
     fee_paying: 'No Fee',
      completion_Prog: 'N/A',
      activities: [''],
      lat: 53.3921439465229,
      long: -6.32306232071899,
      website: '',
      seqNo: 0
    },
   15:  {
      id: 15,
      name: 'Colaiste Choilm',
      address1: 'Dublin Road',
      address2: 'Swords',
      address3: 'Co. Dublin',
      phone: '(01) 8401420',
      school_Level: 'Secondary',
      mixed_Status: 'Boys',
      fee_paying: 'Yes',
      completion_Prog: 'N/A',
      activities: ['Basketball'],
      lat: 53.4525052650678,
      long: -6.2255181795291,
      website: 'http://colaistechoilmswords.ie/',
      seqNo: 15
    },
    16: {
      id: 16,
      name: 'Castleknock Community College',
      address1: 'Carpenterstown Road',
      address2: 'Dublin 15',
      address3: ' ',
      phone: '(01) 8221626',
      school_Level: 'Secondary',
      mixed_Status: 'Mixed',
     fee_paying: 'No Fee',
      completion_Prog: 'N/A',
      activities: ['Gaelic Footbal', 'Debating', 'Hurling', 'Soccer', 'Soccer',
                  'Camogie', 'Basketball', 'Badminton', 'Golf', 'Cricket', 'Hill Walking',
                'Hockey', 'Volleyball', 'Computer Club', 'Athletics', 'Orienteering' ],
      lat: 53.3719942627298,
      long: -6.39106269312186,
      website: 'https://castleknockcc.ie/',
      seqNo: 16
    },
    18: {
      id: 18,
      name: 'Skerries Community College',
      address1: 'Balbriggan Street',
      address2: 'Skerries',
      address3: 'Balbriggan',
      phone: '(01) 8490011',
      school_Level: 'Secondary',
      mixed_Status: 'Mixed',
     fee_paying: 'No Fee',
      completion_Prog: 'N/A',
      activities: [''],
      lat: 53.5791861567889,
      long: -6.11589336340986,
      website: 'http://www.skerriescommunitycollege.ie/',
      seqNo: 18
    },
    27: {
      id: 27,
      name: 'Coolmine Community School- Scoil Phobail Chuil Mhin',
      address1: 'Blanchardstown Road South',
      address2: 'Dublin 15',
      address3: ' ',
      phone: '(01) 8214141',
      school_Level: 'Secondary',
      mixed_Status: 'Mixed',
     fee_paying: 'No Fee',
      completion_Prog: 'N/A',
      activities: ['Athletics', 'Badminton', 'Basketball', 'Camogie', 'Girls and Boys Soccer and Gaelic football',
                     'Gymnastics', 'Hurling', 'Olympic Handball', 'Rugby', 'Swimming and Table Tennis',
                    'Charity Fundraising', 'Debating', 'Slógadh', 'Drama', 'Science / Mathematics Olympiads',
                    'Music recitals', 'Study Skills Programmes', 'Personal Development Programmes'],
      lat: 53.3887384917891,
      long: -6.39571734814438,
      website: 'http://www.coolminecs.ie/',
      seqNo: 27
    },
    31: {
      id: 31,
      name: 'Malahide Community School',
      address1: 'Broomfield',
      address2: 'Malahide',
      address3: 'Co. Dublin',
      phone: '(01) 8463244',
      school_Level: 'Secondary',
      mixed_Status: 'Mixed',
     fee_paying: 'No Fee',
      completion_Prog: 'N/A',
      activities: [''],
      lat: 53.4382530582525,
      long: -6.15248338966244,
      website: 'http://malahidecsadulted.ie/',
      seqNo: 31
    },
    35: {
      id: 35,
      name: 'Riversdale Community College',
      address1: 'Blanchardstown Road North',
      address2: 'Dublin 15',
      address3: ' ',
      phone: '(01) 8201488',
      school_Level: 'Secondary',
      mixed_Status: 'Mixed',
     fee_paying: 'No Fee',
      completion_Prog: 'School Completion Programme',
      activities: [''],
      lat: 53.4019244964689,
      long: -6.37934606077867,
      website: 'http://www.riversdalecc.com/',
      seqNo: 35
    },
    38: {
      id: 38,
      name: 'Blakestown Community School',
      address1: 'Sheepmoor Avenue',
      address2: 'Blakestown',
      address3: 'Dublin 15',
      phone: '(01) 8215522',
      school_Level: 'Secondary',
      mixed_Status: 'Mixed',
     fee_paying: 'No Fee',
      completion_Prog: 'School Completion Programme',
      activities: [''],
      lat: 53.3960412535743,
      long: -6.40342122792023,
      website: 'http://blakestowncs.ie/',
      seqNo: 38
    },
    51: {
      id: 51,
      name: 'Saint Finians Community College',
      address1: 'Jugback Lane',
      address2: 'Swords',
      address3: 'Co. Dublin',
      phone: '(01) 8402623',
      school_Level: 'Secondary',
      mixed_Status: 'Mixed',
     fee_paying: 'No Fee',
      completion_Prog: 'School Completion Programme',
      activities: ['Athletics', 'Basketball', 'Coding Club', 'GAA', 'Multimedia Club',
                    'Music Club', 'Soccer'],
      lat: 53.4652333373987,
      long: -6.22460049737486,
      website: 'http://stfinianscc.ie/',
      seqNo: 51
    },
    55: {
      id: 55,
      name: 'Saint Fintans High School',
      address1: 'Dublin Road',
      address2: 'Sutton',
      address3: 'Dublin 13',
      phone: '(01) 8324632',
      school_Level: 'Secondary',
      mixed_Status: 'Boys',
     fee_paying: 'No Fee',
      completion_Prog: 'N/A',
      activities: ['Gaelic Football', 'Hurling', 'Rugby', 'Basketball', 'Soccer',
                  'Athletics', 'Squash', 'Tennis', 'Badminton', 'Table Tennis', 'Frisbee', 'Golf'],
      lat: 53.3891853759158,
      long: -6.11794562331764,
      website: 'https://www.stfintanshs.ie/',
      seqNo: 55
    },
    56: {
      id: 56,
      name: 'Santa Sabina Convent School (Saint Dominics)',
      address1: 'Greenfield Road',
      address2: 'Sutton',
      address3: 'Dublin 13',
      phone: '(01) 8322200',
      school_Level: 'Secondary',
      mixed_Status: 'Girls',
     fee_paying: 'No Fee',
      completion_Prog: 'N/A',
      activities: ['Tennis', 'GAA', 'Gaelic Footbal', 'Rugby', 'Hockey'],
      lat: 53.3871306994664,
      long: -6.10055876820687,
      website: '',
      seqNo: 56
    },
  };

export const LESSONS = {
    1: {
      id: 1,
      activitiesCopy: ['Violin', 'Chess', 'Art & Craft', 'Lego Club',
        'Dyslexia Workshop', 'GAA', 'Ukelele Club', 'Piano',
        'Basketball', 'Project Fashion'],
      lat: 53.5289465480972,
      long: -6.15690613123526,
      website: 'http://ralet.ie/',
      phone: '(01) 8430525',
      description: '',
      seqNo: 1,
      courseId: 1
    }
  };
export function findCourseById(courseId: number) {
        return COURSES[courseId];
  }
export function findLessonsForCourse(courseId: number) {
    return Object.values(LESSONS).filter(lesson => lesson.courseId === courseId);
  }

